[workspace]

members = [
  "wlf-core",
  # collectors
  "collectors/wlf-binlog-collector",
  # transformers
  "transformers/wlf-binlog-parser",
  # dispatchers
  "dispatchers/wlf-kafka-dispatcher",
  # demos
  "demos",
]
