[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wlf-core = { path = "../wlf-core" }
regex = "1.8.4"
once_cell = "1.18.0"
async-trait = "0.1.68"
