version: "3"

services:
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.4
    network_mode: host
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT

  mysql8:
    container_name: mysql
    image: mysql:8
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=password
